apiVersion: triggers.tekton.dev/v1alpha1
kind: ClusterTriggerBinding
metadata:
  name: gitlab-push-cd
spec:
  params:
    - name: git-revision
      value: $(body.extensions.truncated_sha)
    - name: git-commit-message
      value: '$(body.commits[0].message)'
    - name: git-repo-url
      value: $(body.repository.git_http_url)
    - name: git-repo-name
      value: $(body.repository.name)
    - name: pusher-name
      value: $(body.user_name)
